variables:
 BUILD_: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe
 OUTPUT_: $CI_PROJECT_DIR\build\SearchTrie\release
 TEST_: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe
 
stages:
 - pre_script
 - build
 - test

NuGet Restore:
 stage: pre_script
 script:
    - set NUGET="C:\Program Files (x86)\NuGet\nuget.exe"
    - echo %NUGET%
    - '%NUGET% restore -NonInteractive'

SearchTrie:
 stage: build
 script:
    - '"%BUILD_%" /p:Configuration="Release" /p:Platform="Any CPU" /p:OutputPath="%OUTPUT_%" "SearchTrie\SearchTrie.csproj"'
    - '"%BUILD_%" /p:Configuration="Release" /p:Platform="Any CPU" /p:OutputPath="%OUTPUT_%" "SearchTrieUnitTests\SearchTrieUnitTests.csproj"'
 artifacts:
    paths:
       - '%OUTPUT_%'
    expire_in: 10 minutes
        
SearchTrieTests:
 stage: test
 script:
    - '"%TEST_%" %OUTPUT_%\SearchTrieUnitTests.dll'