//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Global.SearchTrie.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Global.SearchTrie.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #THE UNBOUND BIBLE (www.unboundbible.org)
        ///#name	English: American Standard Version
        ///#filetype	Unmapped-BCVS
        ///#copyright	Published 1901. Public Domain.
        ///#abbreviation	
        ///#language	eng
        ///#note	
        ///#columns	orig_book_index	orig_chapter	orig_verse	orig_subverse	order_by	text
        ///01O	1	1		10	In the beginning God created the heavens and the earth.
        ///01O	1	2		20	And the earth was waste and void; and darkness was upon the face of the deep: and the Spirit of God moved upon the face of the waters
        ///01O	1	3		30	And God said,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bible_asv_utf8 {
            get {
                return ResourceManager.GetString("bible_asv_utf8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                       1885
        ///                       THE ADVENTURES OF HUCKLEBERRY FINN
        ///                                 by Mark Twain
        ///
        ///
        ///
        ///                             NOTICE
        ///
        ///  Persons attempting to find a motive in this narrative will be
        ///prosecuted; persons attempting to find a moral in it will be banished;
        ///persons attempting to find a plot in it will be shot.
        ///
        ///                                       By Order of the Author
        ///                                      Per G. G., Chief Ordnance
        ///
        ///
        ///
        ///
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string huck_finn {
            get {
                return ResourceManager.GetString("huck_finn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                       1850
        ///
        ///                THE NARRATIVE OF ARTHUR GORDON PYM OF NANTUCKET
        ///
        ///                               by Edgar Allan Poe
        ///PREFACE
        ///
        ///                              PREFACE
        ///
        ///    UPON my return to the United States a few months ago, after the
        ///extraordinary series of adventure in the South Seas and elsewhere,
        ///of which an account is given in the following pages, accident threw me
        ///into the society of several gentlemen in Richmond, Va., who felt
        ///deep interest in all matters relat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string poe_narrative_695 {
            get {
                return ResourceManager.GetString("poe_narrative_695", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	MACBETH
        ///
        ///	DRAMATIS PERSONAE
        ///
        ///DUNCAN	king of Scotland.
        ///
        ///MALCOLM	|
        ///	|  his sons.
        ///DONALBAIN	|
        ///
        ///MACBETH	|
        ///	|  generals of the king&apos;s army.
        ///BANQUO	|
        ///
        ///MACDUFF	|
        ///	|
        ///LENNOX	|
        ///	|
        ///ROSS	|
        ///	|  noblemen of Scotland.
        ///MENTEITH	|
        ///	|
        ///ANGUS	|
        ///	|
        ///CAITHNESS	|
        ///
        ///FLEANCE	son to Banquo.
        ///
        ///SIWARD	Earl of Northumberland, general of the English forces.
        ///
        ///YOUNG SIWARD	his son.
        ///
        ///SEYTON	an officer attending on Macbeth.
        ///
        ///	Boy, son to Macduff. (Son:)
        ///
        ///	An English Doctor. (Doctor:)
        ///
        ///	A Scotch Doctor. (Doctor:)
        ///
        ///	A Soldier.
        ///	A Porter.
        ///
        ///	An O [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string shakespeare_macbeth_46 {
            get {
                return ResourceManager.GetString("shakespeare_macbeth_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         LETTERS
        ///        by Thomas Jefferson
        ///
        ///
        ///        A YOUTH OF SIXTEEN
        ///
        ///        _To John Harvie_
        ///        _Shadwell, Jan. 14, 1760_
        ///
        ///        SIR, -- I was at Colo. Peter Randolph&apos;s about a Fortnight ago,
        ///&amp; my Schooling falling into Discourse, he said he thought it would be
        ///to my Advantage to go to the College, &amp; was desirous I should go, as
        ///indeed I am myself for several Reasons.  In the first place as long
        ///as I stay at the Mountains the Loss of one fourth of my Time is
        ///inevitable, by Company [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string thomasjefferson_letter {
            get {
                return ResourceManager.GetString("thomasjefferson_letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                       1876
        ///                          THE ADVENTURES OF TOM SAWYER
        ///                                 by Mark Twain
        ///DEDICATION
        ///                                   Dedication
        ///                To my wife this book is affectionately dedicated
        ///PREFACE
        ///                           Preface
        ///
        ///  MOST OF THE ADVENTURES recorded in this book really occurred; one or
        ///two were experiences of my own, the rest those of boys who were
        ///schoolmates of mine. Huck Finn is drawn from life; Tom Sawyer also [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tom_sawyer {
            get {
                return ResourceManager.GetString("tom_sawyer", resourceCulture);
            }
        }
    }
}
